version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./www/src/uploads:/var/www/html/src/uploads
      - "./.htaccess:/var/www/html/.htaccess"